version: "3.8"
services:
  webapp:
    image: nullsoftin/rcnetapi:dev
    build:
      context: .
      dockerfile: webapp.dockerfile
      args:
        configuration: Release
    ports:
      - 8080:80
      - 8081:443
    environment:
      - REDIS_PORT=6379
    networks:
      - internal-bridge
    depends_on:
      - redis

  redis:
    image: redis
    command: redis-server --appendonly yes
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - internal-bridge
    volumes:
      - "/docker/redis-data:/redis-data"
networks:
  internal-bridge:
    driver: nat
